<?php

namespace ContainerHXWPZV7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLuckyControllerTwigService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\luckyControllerTwig' shared autowired service.
     *
     * @return \App\Controller\luckyControllerTwig
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/luckyControllerTwig.php';

        $container->services['App\\Controller\\luckyControllerTwig'] = $instance = new \App\Controller\luckyControllerTwig();

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\luckyControllerTwig', $container));

        return $instance;
    }
}
