<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPg8arOT\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPg8arOT/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPg8arOT.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPg8arOT\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPg8arOT\App_KernelDevDebugContainer([
    'container.build_hash' => 'Pg8arOT',
    'container.build_id' => '5148eb3c',
    'container.build_time' => 1685435112,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPg8arOT');
