<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], [], []],
    '_profiler_xdebug' => [[], ['_controller' => 'web_profiler.controller.profiler::xdebugAction'], [], [['text', '/_profiler/xdebug']], [], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    'api_deck' => [[], ['_controller' => 'App\\Controller\\GetDeckJson::getDeck'], [], [['text', '/api/deck']], [], [], []],
    'shuffleDeck' => [[], ['_controller' => 'App\\Controller\\PostDeckJson::shuffleDeck'], [], [['text', '/api/deck/shuffle']], [], [], []],
    'drawDeck' => [[], ['_controller' => 'App\\Controller\\PostDrawJson::drawDeck'], [], [['text', '/api/deck/draw']], [], [], []],
    'drawNum' => [['num'], ['_controller' => 'App\\Controller\\PostDrawNumJson::drawNum'], ['num' => '\\d+'], [['variable', '/', '\\d+', 'num', true], ['text', '/api/deck/draw']], [], [], []],
    'about' => [[], ['_controller' => 'App\\Controller\\aboutControllerTwig::number'], [], [['text', '/about']], [], [], []],
    'api' => [[], ['_controller' => 'App\\Controller\\apiHomeTwig::api'], [], [['text', '/api']], [], [], []],
    'quote' => [[], ['_controller' => 'App\\Controller\\apiQuoteController::quote'], [], [['text', '/api/quote']], [], [], []],
    'draw' => [[], ['_controller' => 'App\\Controller\\cardDeckDrawTwig::draw'], [], [['text', '/card/deck/draw']], [], [], []],
    'drawNumber' => [['num'], ['_controller' => 'App\\Controller\\cardDeckNumberTwig::drawNumber'], ['num' => '\\d+'], [['variable', '/', '\\d+', 'num', true], ['text', '/card/deck/draw']], [], [], []],
    'shuffle' => [[], ['_controller' => 'App\\Controller\\cardDeckShuffleTwig::shuffle'], [], [['text', '/card/deck/shuffle']], [], [], []],
    'deck' => [[], ['_controller' => 'App\\Controller\\cardDeckTwig::deck'], [], [['text', '/card/deck']], [], [], []],
    'card' => [[], ['_controller' => 'App\\Controller\\cardTwig::card'], [], [['text', '/card']], [], [], []],
    'home' => [[], ['_controller' => 'App\\Controller\\indexControllerTwig::home'], [], [['text', '/']], [], [], []],
    'lucky' => [[], ['_controller' => 'App\\Controller\\luckyControllerTwig::number'], [], [['text', '/lucky']], [], [], []],
    'report' => [[], ['_controller' => 'App\\Controller\\reportControllerTwig::report'], [], [['text', '/report']], [], [], []],
];
